### PR TITLE
Fixed typo in deprecation warning in ControllerManager

### LINKED ISSUE #1687: Typo in ControllerManager deprecation warning
There's a typo here, it should say:

      RCLCPP_WARN(LOGGER, "moveit_ros_control_interface/MoveItControllerManager is deprecated. Replace with "
                          "`moveit_ros_control_interface/Ros2ControllerManager.`");

https://github.com/ros-planning/moveit2/blob/8c29ad9fa3e8a1fdd8e0c8d232b9273bc5754997/moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp#L139

### PR DESCRIPTION
**Pull request by abhijelly**
Fixes #1687

### CODE REVIEW

File: moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp [hunk 1]
```diff
@@ -137,7 +137,7 @@ void TrajectoryExecutionManager::initialize()
     if (controller == "moveit_ros_control_interface/MoveItControllerManager")
     {
       RCLCPP_WARN(LOGGER, "moveit_ros_control_interface/MoveItControllerManager is deprecated. Replace with "
-                          "`moveit_ros_control_interface/MoveItControllerManager.`");
+                          "`moveit_ros_control_interface/Ros2ControllerManager.`");
```
Comment (AndyZe) [inline moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp:140]: This was my fault for suggesting the wrong thing! It should match what's here:

https://github.com/ros-planning/moveit2/pull/1601/files

```suggestion
                          "`moveit_ros_control_interface/Ros2ControlManager.`");
```

**Review by AndyZe — COMMENTED** [review]
Thanks for a very quick PR!

File: moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp (hunk 1 above)
Comment (AndyZe) [reply moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp:140]: i'll commit this now

**Review by AndyZe — APPROVED** [review]
